---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb3
  namespace: influxdb3
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    TZ: Europe/Stockholm
    image:
      repository: quay.io/influxdb/influxdb3-core
      tag: latest@sha256:7ee43dd74137131d71050aecffc5f3d3adcdf3288e48ea69fa5f714e7d6b0872
      pullPolicy: IfNotPresent

    workload:
      main:
        enabled: true
        primary: true
        type: Deployment
        dbWait: true
        podSpec:
          containers:
            main:
              env:
                INFLUXDB3_OBJECT_STORE: file
                INFLUXDB3_DB_DIR: /data
                INFLUXDB3_NODE_IDENTIFIER_PREFIX: karls-home-node
                INFLUXDB3_TELEMETRY_DISABLE_UPLOAD: true
                INFLUXDB3_BUCKET: synergies
              probes:
                liveness:
                  enabled: true
                  type: http
                  port: 8181
                  path: "/health"
                readiness:
                  enabled: true
                  type: http
                  port: 8181
                  path: "/health"
                startup:
                  enabled: true
                  type: http
                  port: 8181
                  path: "/health"

    securityContext:
      container:
        PUID: 0 # Run as root
        runAsNonRoot: false # Allow running as root
        runAsUser: 0 # root user
        runAsGroup: 0 # root group
        readOnlyRootFilesystem: false # Needs to write to root FS? Set to false
      pod:
        fsGroup: 0 # Use root group for volume permissions

    service:
      main:
        ports:
          main:
            port: 8181 # Default InfluxDB3 port
            targetPort: 8181
            protocol: http

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: influxdb3.${DOMAIN_0}

    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /data
