---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vikunja-cnpg-main-daily
  namespace: vikunja
spec:
  cluster:
    name: vikunja-cnpg-main
  schedule: "0 0 2 * * *"
  backupOwnerReference: cluster
  method: barmanObjectStore
  immediate: true
