apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db-superuser
    namespace: vikunja
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:nnp+MFEZcRk=,iv:akWMmpDr6pYHwhPghhj8MMUJ6jPe5be3cEEMRnSowRo=,tag:hnZIkmVqmw/HGamZ/r86hw==,type:str]
    password: ENC[AES256_GCM,data:HsF2gXMMgcl6uC+zI3HtP8VnIvlha56qt2cg7JJwJIw=,iv:i/rqCscioj3wpJ1jZ2eUeVrnBp9WAj5xtQbtz3q1Kh0=,tag:7TKbk41ux3anWveGZ94Vhg==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVENaRHUwbk1GMlJGRmNI
            a0ZDaFl2QlRTNDNiYkFpY09PR3k5NHR0SnhjCnpqanhlczl5S1ZBNjdYbVhINndx
            ajBWcE5TQXAweEtQaW5hTGNJMC80QWsKLS0tIG1QTEk3elhWWW9QVkFjb05NZUVu
            NnI5aTRheUUrTlNiQ2pTZGZCRy9nNU0KsogUozu5uGPpfMcuivUzItuRY/Ht3yBO
            c5Kv2RALiHoa3B4OD2HJa+K72J6hb6QOATTD+VKpJIBehmfXhdHSDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T17:18:02Z"
    mac: ENC[AES256_GCM,data:XbOBxz51C79c4Vj0RsboMftfEEWyPGxCpahTl6Zf14rfQ5J0+/FFaF2eLVnQUiTx9a0tf7Oq5UgekLGAzqqOtBeVWnsa/GKEhNwBVDgiQC1FcdTQYkRZ5DwBYsWsTY7G9F/7o2tVQqyyq/jFoRuL+Yfi6NNYMxdhWXtajMKqtrQ=,iv:poe0btVtlEdvafM4BZqJd/dfkR1oHz/EpngrEulMN1Y=,tag:V/Qq+ZYKTQ/SOHkRAuWMKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.2
