apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db-app
    namespace: vikunja
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:L3xq4s5uEw==,iv:h4a3+GrLHKMTJarcCU7F5tSwddCacfKvQWoV2m1lGAk=,tag:nKiA4SxZ8BhyI1225Qh77w==,type:str]
    password: ENC[AES256_GCM,data:BaadNgoj/lJIvDq6D+pVJ0MITbBYd4jru2W/SqGbjWk=,iv:hhfJtgZITnc7s6d7lKo0TCAK74HilwCZcVcO4y2UOJ0=,tag:1E/K+SJrB3PQHdRjf5bwaQ==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RFdFanREaDJDZ3A0TnBI
            NnZrb0pvVXNJU04yOG9tMzhnSSttRDV3cDBBClorMmJicHpOMGFXMVpuMGgzWEkz
            UGdCWWQzMjdrUjN4dVdSZko1dFlxK0UKLS0tIEdKbHFQYlBwWU9CRVRjZVl6bVI0
            c2Q0azhWaWtORDlXK0U2dCt1MDhLNkkKuyisPyaMQMTjMq8TNX7Hc081jS8WFyZ1
            nv/B50efhTT86gMpokzMIQyNny0oIkGWfp/C8OKdh3kW9174H61Ckg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T17:18:02Z"
    mac: ENC[AES256_GCM,data:NKwYNJLp1rrFDKzvL7bJlo7SgfmzHxTiEH+Xa6vOuUOF7zSOC8myV13W2iPl9jAWhJrbzNXbYzfUCC0g4N8ZbpIfsviTAR+IHwt0R1sR27Entw6ATvVfETXqw2MDAGCyS6aJqY6N4sei31IrO/0CV+zYd25lZUGzfzOYQdG9CHA=,iv:I6RC9hNWJaAIrjoF0p0rGu7JvTb76xbQZsOz1ndu5u0=,tag:9NBCrvF2ZAqrkZ2zhbDxtg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.2
