apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db-backup
    namespace: vikunja
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:YLoKou1/DxL6zA2xHzdqy8tBLg==,iv:eZghFjsF3c2RDnqFSyR/iY9dSmZmxwDUj4C6FJt0Efk=,tag:4NBQJPXe8J16E+H5jXIOAQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:dH6TlEzh4URyIZEsYuVTwEO39Qs9xcdT8z/9xw==,iv:3/ef/efm0PUxRvj+fppkzP9bmk+MIqYQLNtnmet2Xwc=,tag:RPj2Tpai+X11gvawuarLTA==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMEp1dWtzSTlYa253YWJN
            MGlaMklTZVlrU1hCTWcwd2pQTGJCaGlRQ2xJCk1GOUFXTHo2SFBVbFl1Q1k5aDdO
            Ukw2Mmd3V0ZTNDkrbnNMbmpQYzh0bWMKLS0tIDdZMDRwODJDMnNiOElDOHZxMlNW
            R2dMd0kxNnA3TlpUTS9memlmcU1reGsKCP8COcNVeAq56aV/6RKve/a75d82s6nP
            17rFPKPt4zmCmF80FX0WXhGHqvPry8rqXUEBSOeurrvoASUHFZnr/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T17:18:02Z"
    mac: ENC[AES256_GCM,data:8uvkOIUChxXfuwKewMskyZpCZwtxLl5wLaECD55l22ivm7GBW8cqMmcOlV0MQViNw1Ox6AOW4ATviAtquRBJmPVHpMhV9gm5eVnImp3kGh8uidYyWSv6ObGLureA1TLnnhIB5kQox80U5KGtYIvcDuQb1uFW4V1ESdL4gbv5Iqg=,iv:QyNfJn2U+RvXBgTC9exRYjsnAAWEfwY2WILgtAFpxx4=,tag:QbTzz+WlJytDaW9VRx1M0g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.2
