# TODO: Encrypt this file with SOPS before committing!
# Run: sops --encrypt --in-place clusters/main/kubernetes/apps/emhass/app/emhass-secrets.secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: emhass-secrets
    namespace: emhass
type: Opaque
stringData:
    secrets_emhass.yaml: ENC[AES256_GCM,data:LL63Lm+aouJT1m4S6rp5Vpp+6c63gjxBVZKL3MyKFMCArDdLTIL/JhRowNBt+uwqFBBBocJz5YxXz3krJeRDkoH7G8qH2/+yXTHJI1v8ECAP8oStXGZaBvQMQsIbXLmVuYcTg0O4d69IPd/aKL48U4ETykMsWcyRCvIjz15Wn5myXg0clz61igNWzc2yHN5PhPN3OSq1ak/ZBRmQWAq9aUB5q0E1mQGIBCug6vhlkszK0728yI60IRawSH79b0uVLU14OqRO16BXn5UnkQILJhIA6feh6zI/DkBYJw1KW3S0JeCGmbC9D1SMnBmvsRhRBbndY20cw+iaDITBROUsChDgRmO7oWVQ2sii69HRzqHzTQmGNdmtK2QVEUKprACDO1lvyb0Lmj7eUgixzzfY/w4hoomDdrI5CCYbSfFNYLOi8FoGNAupjhoTi+yU1eojg5TM1qJWdEUrzviKFbg/1vs/NJGqQRcnKoYZZQvCTefnEQYdfmV+v4qxddXQCRThmE4tFmg9pFIz7Xic4X9lGmSH/IpWBT5PDdSzx7GiQW496/NKP/dPi6c6ygZCYlAhwCZFkzu6wesk0z3mZJZfLA2/TMOy21CjG4qNXC3r1MdNc/KFTxtg2Ma1aPXxM/7FAiwlzA3aTjGT,iv:KAsuVQrUIKjc1WhwK/CbtvO45U/LjFaHfRfmQZQtzZk=,tag:+m45t1KenxB4x9o6oLK4fg==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQWpTaWN3WDA5OHgycFpr
            VG02WVVSaFZhV080RldvUWFuTmpvYXdMK2c0CnZhK1I2emRRM3kxQ0xZekF5aEI1
            RFlPR1NoMjBwQ2JvYjg0Q3B5ZEZ2VEEKLS0tIHNEVXhDcVp4bnpJWUpoWm16QW0v
            Z2ducnA5L2hDNEs5Sk1aY0NIK04rOUUKQ+uTHHFgkWXB+StWgz+3dGd0Fi6HyPM9
            htfmcRIyc+vciGqIXCfNMx6ZE9H3b9Vg+A3iEGlqi9xDz8PdEfjK7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T19:10:17Z"
    mac: ENC[AES256_GCM,data:18lDVtu27kSH6zCS+w1wPwk2DL/2taAU7Gfhmy8hQt+zIXayxWjvUUpPqASERqPcGAb7bovoDP5jsQzj/glid03qR/x3LL22mFnb8asz1cTRK1sixmIL39KKDWz1En+W9HPFCG+tVPPx9aFhPkxXleirO5wY/LmzCX2SCn39YJQ=,iv:ekck4xRDsBPwLYjcu2aBhQsNJ77KM3lJ/40yrfGSnLQ=,tag:HO53WYDPxP7pZj+pKRPYNQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.2
