# TODO: Encrypt this file with SOPS before committing!
# Run: sops --encrypt --in-place clusters/main/kubernetes/apps/emhass/app/emhass-secrets.secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: emhass-secrets
    namespace: emhass
type: Opaque
stringData:
    secrets_emhass.yaml: ENC[AES256_GCM,data:jZDR+X85xAEzgIqFnC0VYUP1gAuPj+WuRcgmcmcfFkg7GI/j7YnS/83s2y3NrdmLYvJlC/6TuhkRIM8F409p4SDEVfErOADdsMQ5f1EnK5IioOTNtjWo0ljda92wFhmL4gnbYcYicSvOe1HrFK4vbeblVzCun8IqLR0UoJTE596cqsogDtLmyGfBwU/+fqgWhGm8sxgpe3yA4Q4dWpVNNuqOARloLlAV3gUftBEn6Pyq4I3CcHkPmba4N6og1QynK9P23439gNTFNVsIGzBFUuu0SwdeHMTIvwjnp9ZYGvo3s/tEUa3iy8Cf3bJ9zP4n9Glsxnn6IS5P55JjvYRhDOYLOp/VTEz/Hv/aTHXvW7zIHUYapQhfYbJHxSVokqOiJl0E9NNTwI+5qJjHuOj7ZCNo6sQAN8cnlT3sbsQchSjmkTMxHWZuEQgq7xFln7uIMWIXe5ix/y3p/sIZV0VPCn3q+Ke1zCr+/EUSWjn+v9Eqx0kvL5uuDhojggb9Zucn2hmej+w7T0Xu5DWVgthmzDqgaMN/j1l98inAHKK07Egr8HICh3Ql4h6Cy0Zm+Pr2vocoQCfo3ESJafmBXQ0RdiY9BfiUcm95UyVWxyinbKatuKlBAWv/U3MXet88hQ==,iv:0wcx29Wi9VerG35+4H4/U4x+iOR0MJNW7XXrKEHXn3I=,tag:ifUHAXdxtFdeI+rT2fj+3A==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQWpTaWN3WDA5OHgycFpr
            VG02WVVSaFZhV080RldvUWFuTmpvYXdMK2c0CnZhK1I2emRRM3kxQ0xZekF5aEI1
            RFlPR1NoMjBwQ2JvYjg0Q3B5ZEZ2VEEKLS0tIHNEVXhDcVp4bnpJWUpoWm16QW0v
            Z2ducnA5L2hDNEs5Sk1aY0NIK04rOUUKQ+uTHHFgkWXB+StWgz+3dGd0Fi6HyPM9
            htfmcRIyc+vciGqIXCfNMx6ZE9H3b9Vg+A3iEGlqi9xDz8PdEfjK7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T17:12:30Z"
    mac: ENC[AES256_GCM,data:Z+82alg6o67WOGqvO3hP0npzDAijGdnwFxlc75qU7N3HJ9n2QUTXZF/cYtIGib1CjmiVvnU9BsOAfUTEYpoz1U+1y4bpZmCS8I2LO2vxt3HuGh90Get9d0/u/deEE5y0TsaXrQnqY0/jhGSPs38M1mnMxUaYH4J+RiEbdxhrUqg=,iv:FlhTzDUureXNDPtwJ6BUOzvN3/iuktPhsZlhgVtuW08=,tag:bg5irvyP3G81nMY/NnmsgQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
