---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  interval: 15m
  chart:
    spec:
      chart: pgadmin
      version: 18.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Stockholm
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: pgadmin-talos.${DOMAIN_0}
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
                PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}