# Run: sops --encrypt --in-place clusters/main/kubernetes/apps/rebalance/app/rebalance-apprise.secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: rebalance-apprise
    namespace: rebalance
type: Opaque
stringData:
    apprise.conf: ENC[AES256_GCM,data:c/wY3/BYK4NQsfn3rrkF+cC/wBa01D771S7KIuZTEPCQ8Ild2YKKvTlqwjgu8q09bP00aA4kuUq7Brs2qITQJdEYAaETUxNfarqUfBJfgP3av/BgIy2kcLwTlhh3lrvNkIyZOH3p9j+nTYQd7Uy4aso3IJuQ3mYhegJswVpVLJT0YQ9Fc1kWzR6DHR9uQmZqwsPtKOEa1nPCgWYmdqsNODtGixPkoeKfxgg5Zz7dZt5fzLuULk/WSGFM6wCPaEMGADiWjuZW3Dh/LD7UNnBdoXuVsK9J0vuLLya1+t7iYYACJlwFZ6Ku6hywpKQZ2bPb9MhPJ+hRO62ORZ86rw==,iv:EjgAEhsQ1qXAaIEbKHHxwhLdyRXkCGVVqcPnQDOMe7k=,tag:/ansYuCDAADykpyvRKxloA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MHZMZWlNbGI0VnFxYWF1
            c2c0UkhpRy95YnRVa0c2NDRKSDNZSk01eW1BCmZ3ZmZFRVFsbnhHL20vQmUyakRO
            WUFMU0xWK0FvbXA2cExoV1hwM29WTXcKLS0tIEZ6MElNTGhESlVJcmNobnkwUzds
            UWZaY25CTURwdWRjK1lmZWFDWVN1Y1kK9VVHjZirwMTCKY0rVTH/+WK6FMlYICZk
            4la8YOvQOKDN+A1MPYm8wcxn+yOriKYRcXePJ0ds9eI1KOrlt5Yjlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-05-24T17:46:16Z"
    mac: ENC[AES256_GCM,data:XOJI1dsiNnsNexr+xG5r8g6f/2blJ/r9AMXwP81SdyRCOHGxUgtwLDhVp4GPifaNNdQ6FHW52uAsRC4c/TdpYXgtYVabNJ/6Z8ObbNir7ipX3Ilvp78rG52yd0BtWahmONSXFn3DStNAi5L8wf/TWgHC3HQLBzbBBiJh5aX1tAM=,iv:ljAeNBSIkJUZGjS45eJBjC1MtIps1LdODi0Yl2OAEzU=,tag:VghKQI7b77ymT9LECW/jZg==,type:str]
    version: 3.13.1
