---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/actions/actions-runner-controller-charts
  ref:
    semver: ">=0.11.0"
