---
apiVersion: v1
kind: ConfigMap
metadata:
  name: abcde-conf
  namespace: automatic-ripping-machine
data:
  abcde.conf: |
    OUTPUTTYPE=opus
    OPUSENCOPTS="--bitrate 128"
    CDPARANOIAOPT="-- -X 5"
