---
apiVersion: v1
kind: ConfigMap
metadata:
  name: abcde-conf
  namespace: automatic-ripping-machine
data:
  abcde.conf: |
    OUTPUTTYPE=opus
    OPUSENCOPTS="--bitrate 128"
    CDPARANOIAOPTS="--never-skip=5"
    CDROM=/dev/optical
