---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: automatic-ripping-machine
  namespace: automatic-ripping-machine
spec:
  interval: 15m
  chart:
    spec:
      chart: automatic-ripping-machine
      version: 7.3.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    TZ: Europe/Stockholm

    credentials:
      b2:
        type: s3
        url: "https://${BACKBLAZE_ENDPOINT}"
        bucket: "${BACKBLAZE_BUCKET_NAME}"
        accessKey: "${BACKBLAZE_KEY_ID}"
        secretKey: "${BACKBLAZE_APPLICATION_KEY}"
        encrKey: "${RESTIC_ENCRYPTION_KEY}"

    volumeClaimTemplates:
      - name: arm
        annotations:
          longhorn.io/recurring-job-selector: '[{"name":"trim-caches","isGroup":true}]'

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: arm.${DOMAIN_0}

    persistence:
      arm:
        type: pvc
        volsync:
          - name: arm
            type: restic
            credentials: b2
            dest:
              enabled: false
            src:
              enabled: true
              moverSecurityContext:
                fsGroupChangePolicy: "OnRootMismatch"
      config:
        type: pvc
        volsync:
          - name: config
            type: restic
            credentials: b2
            dest:
              enabled: false
            src:
              enabled: true
              moverSecurityContext:
                fsGroupChangePolicy: "OnRootMismatch"
      audio:
        enabled: true
        type: nfs
        server: ${NFS_IP}
        path: /mnt/lundgrens_data/plex-media/Audiobooks/Originals/automatic-ripping-machine
        mountPath: /home/arm/music
        targetSelector:
          main:
            main: {}
            arm-perms: {}

      video:
        enabled: true
        type: nfs
        server: ${NFS_IP}
        path: /mnt/lundgrens_data/plex-media/automatic-ripping-machine
        mountPath: /home/arm/media
        targetSelector:
          main:
            main: {}
            arm-perms: {}

      abcde-conf:
        enabled: true
        type: configmap
        objectName: abcde-conf
        expandObjectName: false
        mountPath: /home/arm/.abcde.conf
        subPath: abcde.conf

      main-py-patcher:
        enabled: true
        type: configmap
        objectName: arm-main-py-patcher
        expandObjectName: false
        mountPath: /patcher
        targetSelector:
          main:
            patch-main-py: {}

      arm-udev-rules:
        enabled: true
        type: configmap
        objectName: arm-udev-rules
        expandObjectName: false
        mountPath: /etc/udev/rules.d/52-arm-optical-perms.rules
        subPath: 52-arm-optical-perms.rules

      main-py-patched:
        enabled: true
        type: emptyDir
        targetSelector:
          main:
            main:
              mountPath: /opt/arm/arm/ripper/main.py
              subPath: main.py
            patch-main-py:
              mountPath: /patched

    securityContext:
      container:
        privileged: true

    workload:
      main:
        replicas: 1
        podSpec:
          initContainers:
            patch-main-py:
              enabled: true
              type: init
              image:
                repository: automaticrippingmachine/automatic-ripping-machine
                tag: 2.23.2
              command:
                - python3
                - /patcher/apply_patch.py
          containers:
            main:
              env:
                SKIP_TRANSCODE: "true"
                RIPMETHOD: "mkv"
              resources:
                limits:
                  truecharts.org/bluray: 1
                  memory: 8Gi
