---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceevee-webserver
  namespace: ceevee-webserver
spec:
  interval: 15m
  chart:
    spec:
      chart: static-web-server
      version: 7.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Stockholm
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: ceevee.${DOMAIN_0}
    persistence:
      config:
        type: nfs
        path: /mnt/nvme_mirror/websites/Ceevee-2
        server: ${NFS_IP}
    podOptions:
      hostUsers: true