---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceevee-webserver
  namespace: ceevee-webserver
spec:
  interval: 15m
  chart:
    spec:
      chart: static-web-server
      version: 6.10.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Stockholm

    global:
      stopAll: false

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            entrypoints:
              - websecure
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: ceevee.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix

    persistence:
      config:
        type: nfs
        path: /mnt/nvme_mirror/websites/Ceevee-2
        server: ${NFS_IP}

    # workload:
    #   main:
    #     podSpec:
    #       containers:
    #         main:
    #           env:
    #             SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
    #             SERVER_ROOT: "/dynmap"
