apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceevee-webserver
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/ceevee-webserver/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
