---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - onecli-db-app.secret.yaml
  - onecli-db-superuser.secret.yaml
  - onecli-db-backup.secret.yaml
  - onecli-cnpg-main.cluster.yaml
  - onecli-cnpg-main.scheduled-backup.yaml
