apiVersion: v1
kind: Secret
metadata:
    name: onecli-db-backup
    namespace: onecli
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:guR7Bg1yYCKDp9GEgd6B4g1ebg==,iv:aXZgoEcAmUt8mCXrvovv8vKL3bwza/K73bSdXYxSPbU=,tag:8Z9YC0NpGkscJUGMYljc+g==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:TnY4XoNpPxXlKB5pXF16i5h8sAAhfx1YHWyyMQ==,iv:LyDF2ecaQ49uJNRUU/ZK5lCwCnyvByCp00fuPuRTk14=,tag:cCWMTFkw95fJZf661yqAJA==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBL080SXd6bmRpTFpJRmRz
            VjNTdHBKMTk1ZUVoVElRMDlTZG9HZlpCb25rCmhpUUxlZUZwZy85VlUzcWlvUFl1
            WXR6TEI4Qy8xNldXQk02aHVBREl0TzgKLS0tIGxDazBqMmlCZko3RVJtOFBiU05l
            N2htYUJTelI5OGZ3LzNxcTZVUi8vdmMK7hsgAvUXPNXeetsENw8pFpJ65xUWO1Ih
            dFdViBh/Ws01PfWlpS0t0r/gDPwckHhKRLuw86yV6brZKyfsq9cBoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T22:42:49Z"
    mac: ENC[AES256_GCM,data:lk9qBgE/iy0iJCIfn1v8pa5mN1us+Wc2uREJhXB/30GFUlyB5Jfwa66UN25p0TqNuOyOR4k+Mm0nY+5dWOeNpUoM+CIilfiwm4yRJXeptduPXbdn16kEW60Y1gJwnxE/bFZi/TqaDSZaRw3ReW61gHLaUb7SgthCySa6jR5DXnw=,iv:T+KlhcMAlIqfPgJrikD1+8awbAJWL25thSFJcNYlzQo=,tag:U9NDGdTVnN+heK2i9IU4QQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.2
