apiVersion: v1
kind: Secret
metadata:
    name: onecli-db-app
    namespace: onecli
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:RasZ1t4P,iv:zvw98AOuHFcsioOkxK9n2kU4XEDeKg9o77IzgmdJvI4=,tag:vg7kX7ucJlLbWj79ypGVxw==,type:str]
    password: ENC[AES256_GCM,data:+xNX14lEMHwoocsOL3WJb0wWAmArR4N1oYiF98KUjAA=,iv:2XCzso52zWQ4Re5htZW5NC60pQBEMzQPfKvrjqN47PY=,tag:2ORniYhECjJLECxF0jab+Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:3KZkU5CcZGOQ5ub/xmlHBBqEddSA2hUvv6o8Rsiak31m8jmJim9GrrP7A8QG4OVa89WIquNjJUmWJgx/wD/GY2cy6RoQjhyTINlBt1KX/h7oPyIB,iv:WSs/TGDfMBBOHLWXshK46knxjeMCsEU7TsyiIBYRlGs=,tag:qsoYHOPQeURRgfY4GiejPQ==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSjBETUx2MTNNNmRjTGY1
            Zi9wRlBJd215V0ljSEJqcVo3eFNsME51QkJBCm0yQzErbmYrSWtiN2J6OVAvazJW
            UkFsUFNVRFN5aDFvM2ZDczF5OGhJc2sKLS0tIHdmUWc1Zk5Ub1RnSUJKVnJQRFdn
            Mk44QU50UVNwYnIrYzNoN1g0cWJiQ1UKiQEcDEw5WfaBmo4iahJ+bhKVx+6rDJo4
            jTXGAhEd9pKikUZqCTHMtOw7OQS7djNPVnH43Zr5PzEAgv8GEiA3zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T23:14:36Z"
    mac: ENC[AES256_GCM,data:UItvVQatuE5EqmCq+OtFXt5Ku/ZlMyGvX9ePQQ2yr9yFezjVwMTxiGubTFeBo27SlWfiupI9os9xdEsHeirytPhM7S0rPhwuUR/jNl/8HJd3fGL25vVM8pVdkF3zGtdBJrUCF//Rl/T+CHOleRlDvIwdRNZ47Z5tsFvbysx3bMw=,iv:ybJv5ZCFrDx8BwWctmkr8lwjZ259MblxQsDyUGgNbF8=,tag:tz5VuXGZONNBbIQj48/Lmw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.2
