apiVersion: v1
kind: Secret
metadata:
    name: onecli-db-app
    namespace: onecli
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:0Zb3ypN9,iv:CucVPK8I2RpwBYkEXwMW/kqPZKA5A2B2ka4ZASduvYk=,tag:Gt1eUsopKynW8KAaibndDw==,type:str]
    password: ENC[AES256_GCM,data:hFW/3wEqBLei9GITWYvaKZx2W0/g0DhPvYABfCer+nY=,iv:6H2OiRmy7bHlnS5RyVIj52+Z/dQjHDVfdWgl4JN6Z/A=,tag:ypiCSqJ3GBNYo8P/z0nsQA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:N9wSmBnxCBIuHZpaGpXMXyjnwg==,iv:AaNFs+9zeX59UGZEc2S3j8yodhELoZp2vflYNDLUxew=,tag:wYGgbkwSMr82QzSCAy9KRQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:9iFPOQ==,iv:spO+k4ThkzacOrji5iY/32nwkD+0MAuznfv7pvHsqKU=,tag:X+CgvQ8ePKdvOK7j6HrDfA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:MT+Gk7nt,iv:sYI/h1uxFRgt2q+ev9wlkKdJgrG67DNpHAslps7QOgc=,tag:LnRgK807zm4CKfaODE/WYw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:lZHF1vgb,iv:4s4s88ZZz6j28bjxzMrX9XkaeXbtGeZ7Qwbp4pgSIwc=,tag:DbV9FoU0D3k3YkauIJkjRw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:wCz346B4TyUqlujeKEX6kV3TUaQuPtR1xmE8jPo86W8=,iv:qKP8sKNu1ZEgXSFfXzHVgx4X/MY4MTNtqXKcSWJmMkM=,tag:7Qv3AiXLvhpCmsTW8pTKBQ==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcFcrRkhJdU0vOFpuN1Y1
            TC85S2sySjFpTWs5d0UzVTBjT1VaVlMwZ3g4CjYxRkZPRnhWVHdlZmNWUzByK0xl
            VUw3aGVlYUNBNGc3V0RUTTRiOFZQWHcKLS0tIE1IV2hxblQ0RVdiTm9EYVlhZ2NJ
            VE43clI5ajBsTHVJS1hVNWluZWtGMzQKM9suEbALK9E9NgMMRgE55+Oo55OIeQYI
            /04dtc3SmBF82Fg2AaAY7fGQw6tE9INVs0c+ZwNV2Qdm+/RFFZPmrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T22:46:11Z"
    mac: ENC[AES256_GCM,data:Ip0zDR1+cqLpqoZ1hY/ltqoDOqlc82jY/atrc75+nZstHGVTQpwoHIN7oM5Dpn4dUvz1tiFMQlomoYVOatsETXK2XtuBjiDQvKMlsebFGkA8bxZ8HXOQbjveLOnkhNfRTgombwpy3xjUIYZaNqTebyoW8/kpOuJ6qymB9bp+dmM=,iv:6iE9JIaAkS9d8PSJgO7QnkQ0MtUMoJbXb6b246P3wj0=,tag:9iDOJtgiIrvmAqeMxEsyMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.2
