apiVersion: v1
kind: Secret
metadata:
    name: onecli-db-superuser
    namespace: onecli
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:y9r7mdxsvZY=,iv:9BW8HUdGnM4uzbOlRDAE/9mwnd7AzYs31d7zgZHpdWk=,tag:raGy08nDO41lXFq2mTdGKw==,type:str]
    password: ENC[AES256_GCM,data:GgCsO6zCEkJ30Hwh49H49MjjfogEkyEK4YfaZpZ2Yzw=,iv:h1fGqE9vXBlzM15MTckcAuciya3P1e8yVp6w4vV9AF4=,tag:45a3e4DZpw9k8r6a51kcjw==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN1NyMVNDSktpWWxydlhr
            UkpmTlpTK0JNVzB6RmFoL2NEMUEyS1U1KzJnCjExc1lPSXJObTJETSt4Zk9xWWRE
            eTYxNk9xWGJlSndCb28rWmJoSi9ZSTgKLS0tIDRpZE5JY2hLSlFWZm1wdWt3SWRJ
            Vy9TZjQxMUxRNkVSaHV3bFRYc1BjNjQK0hj5LdVe0fF1gmBZ7b6P313YpZXoJSSX
            26V8xjAccpuXamiYioQoy4Sj6mz+M8txWkULmui1sm0b9vwPlDFrvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T22:37:29Z"
    mac: ENC[AES256_GCM,data:lv3WsoRPdAwOAfGlhP1D8FEHFCmlT09DxKkiit98tnj42W030XWZHy00n9WHNQOFx5gx7l4QmnBQAaohRDe71tbr6frEOnhk33QZAqAkG81G+rwESrstDwM7mUKOF0v259TNBCyOWF6QfCWC9konco4q9P9fm0jUAesF9/v9T3s=,iv:UY95PVDX1deGnKt1wKzgVx5zt0OJS73ESekqxrqNJs8=,tag:5LQurXmynRaU06YjbCdkxg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.2
