apiVersion: ENC[AES256_GCM,data:HSw=,iv:TVkYKNF2ilczNQpcWqGnZFESg+1A2zXuDU8KNy+/Iw0=,tag:R7iI9rjvN731Y3l38GCC3g==,type:str]
kind: ENC[AES256_GCM,data:WXIDzFHf,iv:wsO1qDf0zq8V4eje28AGMhuq9spQz0/+THS6z3+cRho=,tag:aZPk09iJwkHJhaPDWDCdeQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cAiqmQgCi01uzjBliXS4oYeOKtpvPZ5EYw==,iv:ARWJBnmvOq87fSs3nQ57HnYl10UpBiRn5FXV+wjD+QU=,tag:kNwEyGQ0skseqYY+yQrIUg==,type:str]
    namespace: ENC[AES256_GCM,data:Jpla/y6nU7otTcQbTosWA4bq75En,iv:FlHDc/+lal1NizK8JY/BwNZP0+74OVierw9EEx2W3i4=,tag:gUd+dFmLdI436K4VPITF+w==,type:str]
type: ENC[AES256_GCM,data:+D87Jfnl,iv:CDuGGospRdbZ4UM98GDYy3jZgKGtsQv7oysTV2V6fD0=,tag:PAZOneum+pDZc8kGhVKDpQ==,type:str]
stringData:
    github_webhook_secret_token: ENC[AES256_GCM,data:2TrwtBil381nZsZJ1nah+6tSoek0HRUaILnJqw==,iv:1xn9PgPhNwTbzsRDXVo+QraymhT4gt3bb4lOx+F0AZI=,tag:H3PN8JfFus+/apmsaCXGSg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxd3J5clFXN1o3QmRBVFl1
            a1N2NGI3eWhYZHNneUVack9pVjBJZmhFSzN3CnFoODh6bVNGTXhtbmxBOUh0M0pG
            L3Q3WlN5d2lHQTh3a3U4NXByaVNOaUkKLS0tIFZISGYzOS9kZGEzN2pmWDdqQ1VG
            MUJrU1hiM0wwTXc3Ly83TkQxcDRXT3cKlxAqPPpjX9dKA6A3w6ly2oZyNwl7fUcV
            2IobmvC8ZmS1HMGOyhrLk3KRURrn8uPLDYan6A1rr7l9xrRIO1R03Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T02:02:59Z"
    mac: ENC[AES256_GCM,data:krbdhLXTIs87t20O4NPbApswcl6mQ8FtgijSBniZBhOkB8zHXCBhxKdf4On1GA0cr1XUudiQv/Q3rOT/BlJ9JbBqVgEdhFE1XjkehR8NX3yAO5UMv4BlTD0eRfjCq58WqDb7iFm0BmBH+zqvXGsGcZ4Qljc7h4gNJFF+oHf3BUg=,iv:SjesguyuCwWefN5z9R7gFZ5vR8CliDjmvT4Z7NJTivQ=,tag:VqfKej29iZt3XtfEJjhHUw==,type:str]
    version: 3.10.2
