apiVersion: ENC[AES256_GCM,data:5S4=,iv:5bszGAb61o1AtTEv0KbJKyEbLmuOuxArv4xAnhTcT08=,tag:S4kUtBGhEKG4z6icNSMTQA==,type:str]
kind: ENC[AES256_GCM,data:5IrAz8i/,iv:Asci4Xq+goF4vM4T/qz0+deP9fsDmyt+O0PT1+eAu/s=,tag:j7NYI5S8CJCE5/s+gZatCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OBeJw2KnoUF1fY3QnBW479LhtkpGlgyL6Q==,iv:F93vLwkmJgJCsvvG1ZJp7p2zO9Ar31qZ+2yiKZKXMAs=,tag:s00arL34DVdayZX+qTgv6A==,type:str]
    namespace: ENC[AES256_GCM,data:0sGHBbVXK1+LndRzspcjz0IOhW2U,iv:ik4XVYrEq8f2Jo+g2+zJXcbI7egeTKOs9v0vqcgdyqg=,tag:1mt08IN0m1x2HVhtTDRM1g==,type:str]
type: ENC[AES256_GCM,data:6AmSHlpN,iv:zyfGv0kckGcvV35NyGhqSIvF2c/IL8bLqzj26GGaiZs=,tag:gC/KlMWohuOFe+Ln8mPetA==,type:str]
stringData:
    github_webhook_secret_token: ENC[AES256_GCM,data:9jAt4J9cJhv9QYiOr09uo2oCPnMmlmbV8UJLlg==,iv:DrqmSHK30OOq7mzDkPmdlpWEBaQQp6q0eMSYtwPbyvM=,tag:iKXtKLAz2/Qa8weUhwSP4g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd2J3b2lUUHBBcy90YzR5
            WXZLbXg3OGtDUU1KQ2N6T1lvLzlySmZ2ZURrClZkY3ZlN20yNWRpU3JwdVk0YWhV
            aWNVOVJyUWlGbDVFdTJJblRDMmp4OU0KLS0tIDJZa0V6NWRqMWVDdFA5dmdJY0NC
            MVFNMHRITFFpTVdOZURwK3ZjUVlUTTQKUcr5dF3P3K0oBi+MZu8urkPPMk1OMfaQ
            e4fmDO7MvzhoUlocaFvzfR2AlpZoxDNAoxkSMlIBmvv3va7chUEzjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T01:21:48Z"
    mac: ENC[AES256_GCM,data:UftrYFMmMSQz0ELSOs1vGuyIsKyvTCaRGXENnp7dpJZq3hpESZAR3hBleZGfkFFDLIicRknQ+T+H7JDkbCurP4OOgnV3R34/3NVLPRM5LiOHzUOpvnENDD0pn4Azx1TO2/K7+AnNWGcFota+JXyXQ+uf5/a2V94IJtPNVGU/Zvc=,iv:AaPtuhlEGkPMfApJKa+lGHG54ZhbDZLl9ROck1ze/+o=,tag:yBqG0XY3IXQE2ZdyF+5TCw==,type:str]
    version: 3.10.2
