apiVersion: ENC[AES256_GCM,data:mSI=,iv:LqonQ11ky9Dpd8Oz3htKqxzPJEjgjNL1PK5CS7EbrbY=,tag:EjZAj4ZR0yw8nDdSz5P04A==,type:str]
kind: ENC[AES256_GCM,data:cxPLmXFD,iv:mfv8mdD1EpDkCch6paEMTz8ytausUMS7e++O1pUAbkE=,tag:l7EImm+cOJ64rpgO7ZMvnA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:b6AiQfc/ZXAKDRL9SoCaIC1ze4uzcOMZoQ==,iv:8RVUk5b1qgwGVUM6ixJvjMQaoxbEhA2kl3AJfnj58jI=,tag:LV32bfolX0lC3RC+ISjC0w==,type:str]
    namespace: ENC[AES256_GCM,data:mvUyKk5U19tWCC2jbnBtJpzsx/lC,iv:ntY5UlMLqs+Paiw3kFSqXzvkE2XXUJxVffLbjEr7DdM=,tag:/OLMpEZ6nmeSbKLYrqqKdw==,type:str]
type: ENC[AES256_GCM,data:V3FxvswP,iv:O6hYPzSJIKQ+QOORKZXAG6aQmkGlfPhIlf8t1/D91jI=,tag:h6BXwYLDOEEqswbFJCfkEg==,type:str]
stringData:
    github_webhook_secret_token: ENC[AES256_GCM,data:wLsJx91XUlZKN4zV4/ZSEw5zuInKwvXzYaOy5Q==,iv:BEozoRmavW1bbP65QeZpI8NpEMwqznOntDwQhLdOhbA=,tag:KLmjoRJWMRCswbxCPDbmzA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ0p5aSszWmd6bWNsbC9s
            cnBMRlFtYVZyeDkvYnRjN0JWSUs3UTI5dFI0CnIvNy9QTDN4WExRUWRSeDVZajMy
            amtMSDhvWnNhVUV5NjFNNWhpSFc3NjAKLS0tIDFDdUpFWVpBaTBuM3ZMbzdCS3VR
            SllQRld3MWtWVzFRNmJvYTVzVjZyTVEK9mwmKHDyV09g800Lt0zu9l/pwX3PYg57
            2qKwQG0pdgdUiojtolXqIMKFwgKpBkMtlfSIGMZjeurfxAl5nZ8T8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T00:47:02Z"
    mac: ENC[AES256_GCM,data:HgwA4cexblMC1Vb3ViBCxFw72H6UH3MpqKtzSx/uo7TbYQBKa0rAKXL1iROBxKkpXaVhUiLZN6nHZPfg54VsgEOYqO27crymmUhS3+52AtHiegANc31hGkb6Fgn1b5vYdp+99dcT/CrpIx4Z4+Wiuaz9swlkPtGHy3obthF/IiE=,iv:dfIM7AABRbUGZqyf4MKMwDwSEpst93Zvoxa8nYKHzaQ=,tag:78I3RIErqMBvZkJ9TDcr6A==,type:str]
    version: 3.10.2
