apiVersion: ENC[AES256_GCM,data:b1Q=,iv:Tjova5srLJbJdfTYv8a+1aE0idXNjCsFfqAGbNAWlpY=,tag:LtNMVaNQaMqVtOOBUFZNcQ==,type:str]
kind: ENC[AES256_GCM,data:89zDfNMq,iv:U1B0Vl4SOUQDQB0NWyFNQ54lWdsBJqoIhWPg7Eod6kY=,tag:z0qp+2MTXTWxv47PVbwMLw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TZcxX87DXC4JyK7HKjGxuow9pDptcvVweQ==,iv:kcmzrJx70Cw1b1eRmpGi6g0Dad8l6VDQ3Gk+vkux3pk=,tag:dwNZqeXdBS3edrX20xVEAw==,type:str]
    namespace: ENC[AES256_GCM,data:zIzSXreX96pYyiS+BJTr7DyAjf+D,iv:NFUHndUMgzhR/FzbbQf+aqESHHLA5DRZcoPV3yKRM1U=,tag:L+ul9lvqkJkEea0/w79EPg==,type:str]
type: ENC[AES256_GCM,data:zKMjHdRt,iv:0lnxh4MfsEx1MpyE3LHfjSxykYigEqMeYmJ+R1JarDw=,tag:h7rOB5PBWsSVxYzvi1jfag==,type:str]
stringData:
    github_webhook_secret_token: ENC[AES256_GCM,data:2sI/TFpss4K/3Bq1Tz94EopEq8N5DHXZbuyOYg==,iv:uXoaAEYenUalgTtYwtbhuxH9YrSXJN1bTHflj8u0q1Q=,tag:Tloh2pMlcNIBP/hRHbyAXA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOGpNbFF4SU9ZdHZ3ZXBE
            R1N6NkJRb3dwcXptK2lZTnVtNzdrQVJoZ2hRCmV0SDluZGlLVkdUbUFVdkc1MStv
            Y2dNajc1VWtsOVpuZXJsWGM4RnVsUFUKLS0tIERXbjFJd0NHU2h4aytuY1J0SDZW
            NnB1YXQ2cWpGb2hRTThoeE91OWt1Q1EKl5ID3TsvB6jxf/m/jFWlVEPMp2GbisMc
            xOQ8wUXVhe3EHT1hwYbhXlpKerQdE+AWN5IfctEo+sLoMZRQfrcdnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T01:17:55Z"
    mac: ENC[AES256_GCM,data:1kqAegBu4yULd7szB0gdRVlATqXR4fKiOmGBhhzaL6Dx1tmMSU8ajZTLfWmnv/KWj34o9ZHvmuylCV8T0kSL4qW3l3qYZg3M8RDOXGZhrw9B6tvUt3TjXdOLqDFiRRYKh1KHdIe2VBREkisnRvwwcfovyYPBYM7kEgPnn9vraDc=,iv:6KOY2N+1RHyClyirzrBvqIQdd8NsAbLZzqS6h5cjGAU=,tag:9snL4RD6QW/06nDss5a3lA==,type:str]
    version: 3.10.2
