# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
  namespace: actions-runner-system
spec:
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
      readOnlyRootFilesystem: true

    podSecurityContext:
      fsGroup: 1000
