# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
  namespace: actions-runner-system
spec:
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.12.1
      sourceRef:
        kind: OCIRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    authSecret:
      create: false
      name: arc-github-app-secret

    githubWebhookServer:
      enabled: true
      secret:
        enabled: true
        create: false
        name: arc-github-webhook-secret

    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
      readOnlyRootFilesystem: true
    podSecurityContext:
      fsGroup: 1000
