apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - ingress-webhook.yaml
  - arc-github-webhook-secret.yaml
  - arc-github-app-secret.yaml
