apiVersion: v1
kind: Secret
metadata:
    name: vikunja-app-secret
    namespace: vikunja
type: Opaque
stringData:
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:IzesCqkRWyZLPdC57MSVtVS0g9P9wkl0mr3b6JxgVnFHkYIsplno/+aNNmk=,iv:qXxbSDdZwHOsL7f+Yu+Lyz+8Tkge1UXyzoZaRWaaASI=,tag:9a5V9C0Oqn0oLmxG3t2GmA==,type:str]
    VIKUNJA_MAILER_PASSWORD: ENC[AES256_GCM,data:e6+zqF+QwyClRx39ZnMz0Gh0oDI=,iv:ophsn+1NLtXsmkAAevLcGiz+g2VpLQvkIXCz35yWrog=,tag:LohkRKD16cjjYGOWpaW7Ow==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydEFyZXVBNkxhL1lYd01m
            U29CV2FjNVl1dWJUUm9PSEY0TnMxREoyWEVNCkNZUXlGYVQ5YmM1cVNDVWZURUhw
            WHdJM1ZvTGdXc0FVOVdJQVFpUjVnUncKLS0tIEJqdzB0dFI0bmJ2TFErNFRhU3Nh
            SWNnQ2szY3pGNDI0VUI1bkdhNmpOTzQK0KQoLkJLWANaqPGNX6qzFHy2wm0szHTm
            CTcHBFM5zo0X0d8smUN0eOr/7eHRt0Qe0RwLHLDIK32rdrD9kK1qUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T18:09:02Z"
    mac: ENC[AES256_GCM,data:0BuyZ+3lCvGtk5SUUgOA2KxEEtaeJe1ifYAoz4lBqSTX+J3IjFJ+SznaRYHU81E/1zffCPTziIJ1+ky6oKbFkD5cyImQK9PR1fd2mJNUX6x7v47LaGtZwNBlZHZM8KFjcrcJIQl04Xeyb/ajyj3uZ31qhtaU6XorRCvByGy0eA8=,iv:cWWcO5sjoOY6J0I8chKtW2zItcbg+w/msNx8EyxkAbk=,tag:c/dBwqgtifDHSIi+sDS8zw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.2
