apiVersion: v1
kind: Secret
metadata:
    name: vikunja-app-secret
    namespace: vikunja
type: Opaque
stringData:
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:8G111VsBVQ2HB7+82oxQlnWvnAimWduilUvnoynWYZwXRIqI79n2/i1TRMI=,iv:Fd71MpStpBHS1Fm8oLJe2ZoAWZsxTXhOoJnP7mf50OA=,tag:QNduDPbKbgRPt/Lvauq56g==,type:str]
sops:
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUzN3UnUwUFZEZ2lrMmp2
            ZGRNYWt2TXNpOVdGTEM3NS9EVEpRTExkbEdRCkpDbkgrOGtrN2RsWGMrQXRybU1q
            LzJVVkovNitzei9QRDZ6bXY4NGIyYncKLS0tIE41VHhsbTRGK2VseFMyZ243WHh4
            TDdWdVhlZWZTKzA0clN5TUQvMG1uYlUKNVENJLy2C6gXDBb4MLvaSAsDkNYfEGg4
            lsdcoGxbfNQ5xsKJr6htMGy58gr7Qs10Y4fJASp39Ec7UEsmZO4rgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T17:19:22Z"
    mac: ENC[AES256_GCM,data:Gj6gSF0uwhVK9bbiIxlPZyTDB7xD7cxj4hDBAzUPsWAUTcRZV5MZnS3iv0y3i85uEwVYgK3l7KfXADdBBaY6q6pc8p41C8o7y8NDMWAy4JoUA9H7UiiOJCuKUc8Sd2RW9pMj4T0Ked5x/RAfyrjrcE+8DuDNrYeSGPEp1zYgtDc=,iv:b19ZMi8g4BaDIj3/yaJ5Xov+de3VauW2KOK/88IoExU=,tag:kCt4jgjzvdXVZY3ByDIzZA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.2
