apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:nMHktOmzGQIFGFPQt1oz7LvUetOawm2gx3P7VQ5Jv/Xn5Govi2f4A8Gcu/g+fZe/N69FWPsb0uB7clm2aiTnCNY=,iv:uE3Z03bh9xtzrHU8AM0YGnD5pnoStqZ+2j63ylz1KBU=,tag:75Q76+zKTsYgOQweMkSgfw==,type:comment]
    #ENC[AES256_GCM,data:HaMxiegNybEPWCXqDoOd7HspvjUmWqVZnXxF/g6JsvuLu0Ks4dZ8Iu4Qj7s=,iv:ocMsYBt/9kfRstfs04Q85jtnQvplAxRxyiPCDcbvO9c=,tag:mpWsuQjoXs5QCPLYlgeXEg==,type:comment]
    VIP: ENC[AES256_GCM,data:RJ1qv/rbAfeJZSlZTrk=,iv:fFZbcJf6UTvppFdRbGSr5PwYFbTTpnVXFnOz3899kQM=,tag:8yJEI3UVm86QRD6XXVh/aQ==,type:str]
    #ENC[AES256_GCM,data:AyiLGg4x1aZkZtfqemZwMO3Jsaj+hHawDoRp,iv:NPm+kvKc3/cNUDMfzVFGictzTptIYue2K7kQiEccSRo=,tag:Mk2DDG7bqk/9VZTJkLVZ9g==,type:comment]
    #ENC[AES256_GCM,data:Xw1SJXmIvZ0gUM6kSFqkdoVcI22xjkk7roRQFnfoaKs6RnLGlgl8r+00jSsDCwPVBz1Jl4aq+5rKhwqpOoeEDTZiFlgfpggwqte4F6H+Gnm7dIfMDH8MzEQ=,iv:Iy4q1LZ1NC+5dfNjiOgW4fi55bDa/gmZ+Eb5d378TuQ=,tag:i/+Kj4qylfjDFydzIUyI3Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:WxBpa0BhzDTLilFsfA==,iv:Zr404gkpXrh3fL0GV4ccA3Mn9n9gvIdtqaonmwVa21I=,tag:tkAR9TH+WvOiYUsZbN2IEA==,type:str]
    #ENC[AES256_GCM,data:MCr+ImyWbufcqd0k0937mszhkH4a4DbDwmH4AdLlyAX0NA==,iv:OZrIDRbBhM6irT0LAjVGuwxFeW8a4AO09TO7G+dSDHM=,tag:lRz1sQgLIDGRspjyiKqvAA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:QPIKYMC4i2JkWSMG,iv:hyUKisBKy7Y8aoT+EZUGaLk0C/i1OGvE/La1WTelQxw=,tag:onVLIVL0lczLSrbQiEeAVw==,type:str]
    #ENC[AES256_GCM,data:MUQlwFKdBAUoXHE1ZUfLc4xYhPSMq46EsTRiH2/+8VZtB20NIncnPySfrKMKxH8=,iv:MqRkl0jSVe1N51SxdwNIC8HVXDFmoa57m4uJCpFwHoA=,tag:VxjW00nvVngLEebjM02OmA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:l0YlpZhFSu/+ksie3tdtmgjxjSNA746fOtewgmc=,iv:9g1pMO5WVyweHjpttxxK3ybx2gMeFA44ZzTsSIXOjTY=,tag:86dWOzaH7aKNoeyjkz9u/A==,type:str]
    #ENC[AES256_GCM,data:efLNE5yo+x1JdbcYUfOxCoACfN55EJWK0KoIXbsgVq1+sq+ahNvloJCBbHK87cOM9aHr6NDtKZl7Tu2qspMasW9IxsFcXI3GUNKKNBbbIxEbuQ==,iv:i8Ff6GL/Tg1XK2Wv8j+c+nEAmIYiUn6QDf62FyWvfnw=,tag:B8ClS/rBmG9r6k75XwdhLQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:/KrN9+hUwW4oDAx3w2w=,iv:27zUhPHnDpwehpr3Xhv/VWL6eEtOdHiHqJYNeYfrGcQ=,tag:OumsNPwZTJ51FVIIkckx0Q==,type:str]
    #ENC[AES256_GCM,data:TlRsrCt/RVxiRgcoDdaW/dbAe6xeB2EOcpdnEmyF+ij5,iv:VLaTV1FxCee9r/EewCyLJAMP4m/Wmh6EFfM5bQhl+fg=,tag:b6CwDDKzfOXObpdZkPfHqQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:RFnhFUK6yQtjSuswnhY=,iv:Eg9Ffke7WLXTSx6pJxMVcDloEwfP1a8XBbfy1Q/odhw=,tag:PucSFAiAYHsef5/syvf2cA==,type:str]
    #ENC[AES256_GCM,data:KPeM0sw53H6/rbxDIc29URK3gsW8gmcVpGzF4vYEZia6i/9j1Q1LyufKQHwA+2kdMB8cb0ra3LQdhvAPYUbt3z5ybNW1DkuTstDt/guS4lQ=,iv:lhavrjRhnQ4b8Kc2HT1/fQCPSJzRq27k+/5nbk1us84=,tag:SBevXJy7VacwXFkKbpcpkA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:O4Xf5auhUxHIEGkwZGE=,iv:l1DD1BiaeM8btBso+nwmMW5Tz6yCKR+dwxRBDXDr2fA=,tag:laaOr/8gVVtdyTpH0QJwVw==,type:str]
    #ENC[AES256_GCM,data:bvpf9I3cBVtnH4b/0u3JCIHYaL94Fye2KPP6yFnVVZNNzsQvUBOKh+yav7ICOg5lAS7jj8O3FZvOwOhrLHn2FV1y4NA+4h5VZ85aAhEJFxVpw5D7/Cf8,iv:yqGc9QNmFpuwQqErbnVeD2+6utrT2sLkA8qJt3AJutQ=,tag:ELduLz45CK/Bkw59PcC2Kg==,type:comment]
    #ENC[AES256_GCM,data:yAEPZ5ojlpaCP0NbU05jNRKwd5usytnn67CJceFfgouP2aFHyQuwZ3kGtev/6TJc4mEhSLb/EIDwEm4jj/mYAFhe9o5b92Okgzd/bOXIZWfbJCus8pIDeWkNKiOOBp4UzjH3b0RkKx9eNJzz849Vx26cu5HXlsMudI2g6w==,iv:yaa8X4K7tbjnv1+V5rsJNhkJrBbp8kGY+YRYcWVWi3Y=,tag:ZYsYxguaD4dEsq001WteFw==,type:comment]
    #ENC[AES256_GCM,data:DK8/pZ/xUmbZrxN67TOcPYfwiGsuGxM0ucxXxNY1vYSvIwSyXzwIFll1AIvLEGaYCp/DJA2Pp+d13wqNQknnUrZKej7wgGt1/xRC1mlWXKs=,iv:n8bcHkZSKp8aKirDn2RS2XjKLL+ygWuabAnR2GSVToc=,tag:f3/OVAVVWonB1ucoVV5ddQ==,type:comment]
    #ENC[AES256_GCM,data:4WflR3fK9Myh/ZDwZMJS5K+4QYWYynZGZMfHztgw3uIchkeuvz4WJE34o61ACVza/ud1BFiE,iv:5wd+0gdurbx2ihJThiClVpr/4RdFMXHtejK5Z/gHgDY=,tag:BzEQVEBlpnTQC6mbB+Kczw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:DY0m8UG/St19xP40qg==,iv:o4asW7UdCw+QnCJsH7y6ke55g7EvJc4AkX8hJmXPw18=,tag:hqtsd92JlH7lL3bt86hgjA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:K8GJsnT+sQj4irdw7wXTh4/AZMV2qN4et4w=,iv:PB4Tdcn5jxMcpPuD6G5SHmPqxbIBizqX+ybqPu6aUlU=,tag:CFs9S1mzS4rmO/UWCeI0sg==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:dAi2C/HAks/PDepHFP4RYjd/InEalPEx85g2FBICjgh1hhZnklc5bQ==,iv:G+xMLD2OfWmP3CjxXSsFJt0UNHZbJRPdYxie7z96J9E=,tag:EZNpJpVTbMxiM6BEf5VxYw==,type:str]
    #ENC[AES256_GCM,data:RVN5/kH5EK6SFsWjLyYn21QG5sI7XVDHQeqrCgnRLeMS/+04TbJIRvewmv2DpaMWpvyUmCw/9r4=,iv:5qYBJJwO6QUS7Ye37XTJtB/YbPzKb6atpO+2FkRPO20=,tag:wFEvfgl7FAGBx/9B+95H2w==,type:comment]
    #ENC[AES256_GCM,data:ZMW6kPkDp1n9QbOLaQJEiQcZU4s1iMoeHA==,iv:Ka7SwkDRrJH4gPh0IE20sSTndGlHN5P7v8/dI0cCiQU=,tag:X+P4cQ/CIUvYQsCfHC3x/w==,type:comment]
    #ENC[AES256_GCM,data:GWVPReIoMVJKx2QfiqIuVAJa5XwjL223BG2m0vWmprIw3fc2drBZmrTSyCx9hncDElHG2H0HN4ep+ewS2+wAex25XLbc6gIfmpTFfnQ=,iv:45ZfimnMnl9hn+rf2H10q2xEiS75KfYnZn9IOvumde8=,tag:org+zJ/xXfU9D+Qi5p2hRQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:BJxCT5P6DhZFM68M/MeYuNXhTnekVLO1ms4aJ7675q9dWinCXJLqhHMc7fk7Gw==,iv:HX2uFy5fWw/cGs9LhIGlQ/A8fAb/sqPoSOq6iN4qgaw=,tag:zIt8h82aNgYMzf1219Copg==,type:str]
    #ENC[AES256_GCM,data:jkqrdBoNOgmF1Sx4JkS3IZUzAdk+YMhsUeee+IemIGErV4NmmskyU4ayl1fo+CJThhi36MMcL88fb/h3qE64BT42WuVH6OY=,iv:gZQXZIM+vleRLT7miAptbTH/Gn3AttUGJzg6NbkwrMI=,tag:0D/LsQWAm0dJvU4CupD5Og==,type:comment]
    #ENC[AES256_GCM,data:+76EbCWW12R0sMjKYKiLo2m3Ko7D4uC+9tUw1Us0wiztaQS4G9OyRQ+shBJ+Tu9SAu81MbJR,iv:Ap4sfn+NLsdCOjeCAF5Xw1k/NUyrxlYy0Mlu0JaRYGM=,tag:A+2yk45pzbAo/gagZR4+rA==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:o14dds1G6BksjA==,iv:V0oFHg9MY5GpY5vNh2YEqIuPhaXfcBhwquwIHVW0Tr4=,tag:W5ZRt5HCmRGDSF6icWDlYA==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:/3kSCbhAKHoCwJZKuME=,iv:FgLjmo21Py97OfZEBhyWeVz0i6u2+dwio7/lFA0EB9I=,tag:gmLIs+vFm1smo2dNs5wS/w==,type:str]
    #ENC[AES256_GCM,data:dL4aj5gOtD/9e/vmF40=,iv:h+eNDMWKLPEk0nJlwKqcmkN2NxtUeLRO+sTZEpVBk6M=,tag:5QeXTyjxckpmHboeWLYyig==,type:comment]
    PODNET: ENC[AES256_GCM,data:XFBkOIeewnkQFXXlrg==,iv:A1UjwhR5NHpolX8oUO95EWcK2GSj0aWavD2/d5799K0=,tag:LpfpsQTtG29cekw13IOCdA==,type:str]
    SVCNET: ENC[AES256_GCM,data:e6D+c8OlBgW2zkVy6g==,iv:HWvMKzqirwmLfxtGbyfBnF/yA80BwoW39cSyU/2Xl8o=,tag:p4Xcyb/AWdwdvh5vKwSu0Q==,type:str]
    #ENC[AES256_GCM,data:3YMCMzCDpbHqzBZ+m3v0X6nV,iv:69Pa/7r6LsCH1hxZ7y1/Wz2bXUjSsi8eDjz9jukfrZI=,tag:bAlp3jkvhAa8h/+BK3X8PA==,type:comment]
    NFS_IP: ENC[AES256_GCM,data:joEl9mGFmdEbjBrkqw==,iv:WVFGBobs4dnwrAIRcOwpvIYJUm+p/O6xGcPm3anKQxs=,tag:t45gpxcWd8AcT06axAv0dQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:/ijkrg==,iv:V7lwcX0WiIhyebr5qEGbidjH4Dykt/FxiRlupDxUOLY=,tag:EgdqUCunttMqbZg/FZM5pA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcjNjQ3lsTk9vVjBCUnUy
            NFdaWWk5VzAzUE9TQ0pZTTVkbld1cWJIaVZJCjhrZTI5d01aODZGcE9KQ2dyYWZT
            TFloWFcxUk92MTlhUFFjUjRtZjgwWWcKLS0tIEtxUGRWd2xRVjhXa2ZYaHZQelBy
            MGpIbUljQlNYeHM0M2hIbkZFdFlYSGsKqBTRNQg/9iY3NlNNIMozb93sJFJ1EK2w
            RgEVsWGlg0W+oh/pEkek07yBFglrZJXM7Krbz6LSQTPT5h2EP72veA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T19:38:57Z"
    mac: ENC[AES256_GCM,data:c1iVIbVJ9epXo2YuFyZT2qgu7hAJdf5dz7/ZkQIHQZkbh8qHqc//uCk51ZSXZBPl9QyTuC1zYZajnNp/EKGNy/PmRAA7s6YXt3wPvLn4iESiGXyxxt96EbJ0vUY2+ippac1WQKg+cmN4P1OSiusvjDk7+a4TutpeWxvQv0LD7UY=,iv:uR4uYWRkGleyAPoSpfCXr5lMqOZVNn+8XsFq6Lw6JF8=,tag:HSEUkNDIfBDZgD08pAa6gA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
