apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:BYS5+hzQgQaJ9bDjCd5fK99vbY/f1XhTb4cy/XWKbPNOKm+pisuTZFuJ9x6SE6ePTJEpoR/5tzCJTy+SutoUv88=,iv:yIbhepx7m7Iwuer/oRveYKxyQe4iAjwlomfDP0k7jcw=,tag:tan6ajKscp8GvAMtS3Gs/A==,type:comment]
    #ENC[AES256_GCM,data:Th3Yjk+h1Fhcv13db+bMVMMr51u4wL01hOKEOOzUoIkEApk1963x2vRBTys=,iv:MZ6oNk2y/P8EVsfBIoP531Ptfl0xyeiu0xtzfZ1ehSY=,tag:GG803uWBVuKWldX0VJbtHw==,type:comment]
    VIP: ENC[AES256_GCM,data:NW11DRPz80Hlj7zukC8=,iv:vL5ir35LsYuaFsMwB89Ya3UePTg5he7odf4OzfpoHfs=,tag:boYuzLlZGBCg27PUlf2iyw==,type:str]
    #ENC[AES256_GCM,data:SggFHaLcUFjr7ijrlEXFKScYaxEYyXFL1e50,iv:vRh/lINjgvcn0dJ9dD+BnlxoNKD3B6G/VNrGwwgw3g4=,tag:nnuEL+PdJli7e5djy5EOpw==,type:comment]
    #ENC[AES256_GCM,data:U2V4cmEQ0sMsiy3l2C6+v4Qlg3Wrn9ZH/0ko6vDNkyzkhhPhEU+WVM228RyRA8Cztg9VKY4tgcQV3eukmPr2MWDcXGRrXicyNbOIMi3KM4XzmkPX5W0PEhw=,iv:EnDOM9OYi4UyJW+e6nIzofjDK9Ut6hy4COZmzo3lIm0=,tag:lm/fyM0JyFwm4XSedykRkQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:ea+l0/qe2tUHpZIqSg==,iv:vfrQfdJ0gyGRq1YMXlrHc4KSw50b6u3pzVURGWiPets=,tag:mAal3lCVLn2ZrDS+wpDKSg==,type:str]
    #ENC[AES256_GCM,data:uQL4Ck7IczgE8UppYJVBxf2XYKLmLg2sQraBfyx7YCaOyw==,iv:Cw5V8aCxHMDLYfFa7GLJGQSEa3YIU6FRhjcPu7MDXBc=,tag:k8hmOrga7EjRpz3gecERYg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:htQWq8muafKvHJUP,iv:63k8Vo7srwtk1SK3TRCVWdUqhNk+DmY8SRBi4RIDJLg=,tag:3N9NynO0c3WswJs8k88Cuw==,type:str]
    #ENC[AES256_GCM,data:WBOdAA8xfLBzfskNeDXm/NoYHYpejb+n+X4XRf2pazDp06hvj+4ALELeYrb11fM=,iv:tiSBDEc3ohU1NzGgLsYUOHmOO0xov++eYhLbGSgqNMI=,tag:MTuxQFgvHxesQDG6jmyNcQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:5/ZV2IKli93LY4WeYvCZZw+dxRh+lJQ0IZaEZzg=,iv:Xc3Qpc65/1tVkYyxxpxIkbyRlgMvlXiRK8KCmSzSuks=,tag:QDha02nmVcT451fWrFFzqg==,type:str]
    #ENC[AES256_GCM,data:IY3/d0M9k8vxRfSW/m6WWvpTUWslR2NzRT+vjKZslbRo7r9nx7Eg+KOKQnyybMQoot1v9ZopMY8CPFQh0NCko1IK5vlq9ALyU8XcgcjjqwFCJA==,iv:sR5r7VIeR/95lwqe/ot+haGR6/6PrXzMWxCxVborJMg=,tag:s/6tkDDDFoi5K4zDD6OIlA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:UBpl0php0nsslks76eU=,iv:JYwGSHHKcot2KRL6tK9t6vuEif5lGoBSIxmDD/FxHw4=,tag:wLzkyNXG3j0AjEgzp59fYQ==,type:str]
    #ENC[AES256_GCM,data:1N3Sqs/r8XjdZhLGrGg1vzV9sEv8gTrwfU64ZaaGRpqa,iv:U2Td+qDiJJIwlXvIgFbHEq/RkQe4wuztE03AUlRzNTg=,tag:pwZdFl5M5nAg4lb7x0UxCg==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:+9zxfN+H6eTUwjWTd2Y=,iv:55z8YGvs6OGd+VarlHb7j/pnParmP6hDQvOUBURZjKQ=,tag:/nu1bAHo4rYmMJb34tAzKg==,type:str]
    #ENC[AES256_GCM,data:WLDuxcOTcTBfUNBlaIdqigMrYuapFEJDPRtmCTkECYlEfbo6nymZLAsxbTNNG4/xOSZR3U7lp5NSbJ3xEUM5zk73vS0zUKNHH/chapxcASw=,iv:AC8o56yijGUHe62fc8OFWpoEeqwr146oB2lWEGb4mgQ=,tag:1q6UozJh1/+o4Ualt3FnAA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:FbSfqINrcdFJdetEV+A=,iv:MEadM5go4l6GCjT73KSXsa4vcj5rnznr2aAOd0zUN4c=,tag:2IYXezNLp/4DVmYVury7Aw==,type:str]
    #ENC[AES256_GCM,data:REQbIJ+vTfidmVzJStyzu7EpBSDYrgNSNRf52yF6yCHSIF36m+p9kBzcL9vhhS6uFf/vDNsm7Yvg9KUnxc+8mEhoEtQ480hZ63jpwX9+Bj+gH4IWpq82,iv:oILeZ+WFgwXHb9F/kRmKxD+P8tSMxnFcGKJCdXGMhII=,tag:HPgR3O+Gn5OdZ0GkdT+LIw==,type:comment]
    #ENC[AES256_GCM,data:ytpAXdoGKSstIkTbvZt2fTs9ODpAgEh8Pq+q6TUYTeF9WP64UD2gIDBzFjhliPyqyN9Q4HVBLMacXpRq3Bi3scDAd+nUlet5W/pjwEWH7c6ZgpeciOtdLYgs2iQ5qL29uaWu9AsFwFOm0OVbB0tI1vYoepVk5Me2oaa4HQ==,iv:3xOUqeamJ4dbNjUz4/r/Eno9whCPdwZ0CTSXzh2GRN4=,tag:Qct2ohIldcTeglFasdl76w==,type:comment]
    #ENC[AES256_GCM,data:F3ZFBZiKTLH2RU3dMwVgNgCselWwhPHAK3f6b/SWXY5b+TA6ZZCLdTVD4E3Ttgd6UtJqzLXxWoRMaUgbhH1Y6L8Ec1uvmcT7lrn7gQpetDQ=,iv:18gtOjxdKxJc15eqf3S3n8byHFAjFAnUKlrXcKhhJXg=,tag:0Hr6o6g0LE/At5VAkUxsTw==,type:comment]
    #ENC[AES256_GCM,data:MraPGQ34Bt9Syji2AJ/+bJfvT2sggWqaWA0IiBFWOOel9caT082gS22NCzCw3Uaw502/M1n/,iv:ffUjcdvVy+qa4YQD+j/z2BCDwN2axernBxlmkdkklqc=,tag:ktV/fROQN851UL4tAdOExw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:1d+J1hXbWIApznkmxA==,iv:PE336lNaADwYW2sxpqTBzoVwbzI633jMB7kNdRqkkPM=,tag:42K3UQ6ZgmO0kcwjC6ycTw==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:YkvbGbVDPhKWwZJMs+8K0jyf2WE3sVvLa9U=,iv:akXydamWoAJs8YFu75PD/AdZ3v1N4MqDgXNdC6tsfOA=,tag:cGrtUpoN0L53kOLKchoIOQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:iNBTCbQBJMedTYvOB+iqnILzOGlJw5uB6m2iOaG4QX3LF2NhalePpw==,iv:2DhGW9xuBeVyvHAP9j4GrkaRheQg99khT485PCWBLG0=,tag:eOo03UJ+nCL8i7FumuWSeA==,type:str]
    #ENC[AES256_GCM,data:m2FaiVBjPUKFQDQsNsAlf80gX0Ax9oU8Hq33h63/1+ocNMQpxS2/bAuVXefSZiM02gnjfiz1g9w=,iv:pWzzl6gUP1tLo7pMoGijxWfmZzBFBi4oV71meRR9sX0=,tag:WDh5eu51u4G5SvSf8Z+Pcw==,type:comment]
    #ENC[AES256_GCM,data:eEzkgybGLJROWuI7cMAGsF57+wilfadUfQ==,iv:hrp3W0K2Qe/iZrAmCR0csth8205Zm1BnApgibFE0jgM=,tag:86yY8b4X+k3klvFcs64uGg==,type:comment]
    #ENC[AES256_GCM,data:4IrSHCzG711YgJ5EYbTkysRMDL4kgqymXDoZBXvDDX189q/EhTukkclGwsjlbHXk2EiOEYxKk3ItmIQll4PSWCFw/1ntl4Jyy3XyHrA=,iv:IPTjJMJWycZVniTIsl04d+PB0QVQa87+Fuwu5wqxUeA=,tag:Jz4rrnu2x2CiLLfC0NZ0yg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:vacmNA/rJZno8wbT4CNbT43pTnImyzEQ6bPBXw4GHNfz3LNm8P1JYPYn3gCTyg==,iv:G8vcVPtUQK3hjTDPIrc6H2VBCY8neglMiL2XEur7DiE=,tag:9wqmm2UIL+RRGb61uwbOhQ==,type:str]
    #ENC[AES256_GCM,data:dtQLyUgm2Andh0EXehR1coKa3HnR6kZQ1DjgwH3HdAsz5vkIwC7yb7g9ar7F/GpwJIa+P8+sC+gp6Kkz65VG23+tCdQV3bk=,iv:kRbgyKr2hyHADoychJAaYs2YQgRn8W+dFyrRjjMlmfg=,tag:jdu6jXCPWlFw59ub7OUJqw==,type:comment]
    #ENC[AES256_GCM,data:Q/gdVXIJVQVxYWCn9xztGfbFdyXX0y1vvqKLmyKFoc34M/UNOIB0+NVeSvYDUoyD04H593X1,iv:UT70jl7FmlIgRr1oJyx/GvSjI/buj96ReYUxGDdyI6Y=,tag:9SJmz9qaQV0bNZmAGRSJbw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:SExO34F7NyncdQ==,iv:jYgDkQ32gTuj7kDUbiplOjoWR1LgnF7Kzo/EFOOvBX0=,tag:P3tMZx40UVT73LawAkra+w==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:K0ENVbGvyffwV0GYGAs=,iv:MKBFzVnHl5Uhd5Bkt57i+cM5loYZ2dMmDx4MNVgsBmA=,tag:xcq4q52gqDxC/681ohiJOw==,type:str]
    #ENC[AES256_GCM,data:C/T22AnIxEJw5yrv/48=,iv:cNaCyF2Efg5d0uRCi6omE8ck4x1XZX9YBKMdU4BuiEI=,tag:+Qw0k0+wbKO+iodgbPOP7g==,type:comment]
    PODNET: ENC[AES256_GCM,data:G2QcS8LiDmkwBxx22A==,iv:5zoZfhRa7+6t4LJlxwydg++xkmXbeyRTc5K2h5hsdC4=,tag:uyUpfKTHXh4i9U7eZ7OTGg==,type:str]
    SVCNET: ENC[AES256_GCM,data:EOOSFzkF5aVRfYJq3Q==,iv:wvHvUqh80fswoR+2MH8bzlLffIcLP7gk+D/MxSHVY+k=,tag:zMgarECzebbqO8S8yJeXVw==,type:str]
    #ENC[AES256_GCM,data:8KGrjuE0zGQA8LHd1nx5ZhkT,iv:K6kkzFR2pgyTSlrCEpKR2zQFZzyPOS0uOFmu4+ZPN+g=,tag:U/p/DKpx8i1WY0LKGcPsBQ==,type:comment]
    NFS_IP: ENC[AES256_GCM,data:7WVHsgFiOXYneVMpKQ==,iv:yb6BeeTfDHBDlQ22HxSXdfNH9R4YfTgqPKcKHyHyE50=,tag:1R+s8r8mDFYxbFhYhKnIrw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:DPqRyg==,iv:U8VehzKYC7Akl+KF+nmZjdszoXFXzWG6XFCEG+Vo56A=,tag:5kUGrc1Y8ErFuMnBsYDn9g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2g32hgsdg50grn8keywhqr54j0u7twyjhvrucvgqcydhqpke3qsa93fj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSzVPZmNrb2drWnlPUmN6
            RlYxSE5CM2JTaFBMQWtVOVVCNlU4TXIwMFUwCm9VbzNJV095UkZoWkJjbWFTNVJK
            ZXBlSG9vdkhaVjFWam4vai9SSTBOTXcKLS0tIE5PZWVUMlFFTXF2RUJDVytqTHA3
            MHNiYVdWSCtsVTVVcWp2akxGcE1UTjgKnqsbp19g08/mXYGC4XHRMb+R8iHvgUzW
            emBtk/Ah/QBMkRFDe8+kmYWMXr6g2Jm1ZYpsuJa0pD0hBq9C0kMybA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T14:06:03Z"
    mac: ENC[AES256_GCM,data:wMQbUDtcS2xC9Fdf+z404k41cKpPy9uB5VqLlWJxq+3vlyrj/Bw78g69KOaeYpGlbPayTPfntT88A6Qt2cyUCEfttql/bkEAq+zPZKRZD6GKHeUJahjvA0XsT0cUDWQkCP4oNl/N+C9f7ItEvhwouxEs0K+paH/bHC7lPTrkaYY=,iv:pxAA04JmQlvT8dktHQGgsKVMsjBB9IoarrKGehANyYE=,tag:ZtFBo/HeWoav8N9hjWU4Dw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
