apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: librespeed
  namespace: librespeed
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: librespeed
      version: 15.6.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            entrypoints:
              - websecure
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: librespeed.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
