apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generic-device-plugin
  namespace: generic-device-plugin
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: generic-device-plugin
      version: 1.3.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              # Override the arguments to define the Blu-ray device
              args:
                - --domain
                - truecharts.org # Keep or change domain as needed
                - --device
                - |
                  name: bluray   # Resource name suffix
                  groups:
                    - count: 1  # Expect 1 drive per node
                      paths:
                        - path: /dev/sr0
                        - path: /dev/sg5
