apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    defaultSettings:
      # Increase to 3 for a multi-node cluster
      defaultReplicaCount: 1
      # Overprovisioning might be needed when using volsync
      storageOverProvisioningPercentage: 100000
      # v2DataEngine: true
    persistence:
      # Set to false to pick another CSI as default
      defaultClass: true
      # Increase to 3 for a multi-node cluster
      defaultClassReplicaCount: 1
    longhornUI:
      replicas: 1
    # service:
    #   ui:
    #     type: LoadBalancer
    ingress:
      enabled: true
      host: longhorn.${DOMAIN_0}
      pathType: Prefix
      tls: true
      tlsSecret: "longhorn-tls-0"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: domain-0-le-prod
        cert-manager.io/private-key-rotation-policy: Always