apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-wffc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"       # tweak to your setup
  staleReplicaTimeout: "30"
