apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: home-assistant-config-files
    files:
      - configuration.yaml
      - automations.yaml
      - dashboards/ev-charging.yaml
resources:
  - namespace.yaml
  - helm-release.yaml
